//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartDetails
    {
        public int DetailsID { get; set; }
        public Nullable<int> CartID { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> IngredientID { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Ingredient Ingredient { get; set; }
    }
}
