//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.Ingredient = new HashSet<Ingredient>();
        }

        public Category(int CategoryID, string Title, int? ParentCategoryID)
        {
            this.CategoryID = CategoryID;
            this.Title = Title;
            this.ParentCategoryID = ParentCategoryID;
            this.Ingredient = new HashSet<Ingredient>();
        }
        public int CategoryID { get; set; }
        public string Title { get; set; }
        public Nullable<int> ParentCategoryID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ingredient> Ingredient { get; set; }
    }
}
